### ISSUE TITLE
POMYSL

### ISSUE THREAD

**Issue by Superbizons** [JattiDev/Musicer#3]
Jestem glupi, a moj bodygownoguard to najgorszy bot jaki kiedykolwiek powstal

**Comment by Oskarr1239** [comment]
jebac disa

**Comment by Oskarr1239** [comment]
kurwe zwisa

**Comment by Oskarr1239** [comment]
orka skurwysyna

**Comment by Oskarr1239** [comment]
syna diabla

**Comment by Oskarr1239** [comment]
egoiste w lozku

**Comment by JattiDev** [comment]
Tak, wszyscy wiemy ze jestes glupi nie musisz spamowac mi tym repo :/
