### ISSUE TITLE
Język.

### ISSUE THREAD

**Issue by Superbizons** [JattiDev/Musicer#4]
Witam, 
To ja, po raz kolejny, raz mi nie wystarczyło, więc jestem tu ponownie. Chciałem wam powiedzieć o mojej wielkiej głupocie i o tym jak spamie innym ludziom na repozytoriach, dlatego bo nie mam swojego życia, a moje projekty są chujowe.

**Comment by JattiDev** [comment]
Ale my wszyscy o tym wiemy
